### ISSUE TITLE
Is Are.na useful as a model for virtual library systems?

### ISSUE THREAD

**Issue by bjornmeansbear** [GD399-OSD/library-identity#8]
Conversation initiated by Nick Sheeran...
https://www.are.na/block/1772411

**Comment by devinhalladay** [comment]
I think this is a great conversation but probably way too complex to generate much useful information or ideas for the library. Should we continue discusing or let this idea die off (RIP) for the sake of progress on the more actionable ideas we already have?

**Comment by bjornmeansbear** [comment]
I'm just capturing all ideas. We can tag this one as just an idea, not something doable...

**Comment by devinhalladay** [comment]
Since this isn't doable and we now have ideas for doable things, I'm closing this issue. It will remain in the "closed issues" tab, so at least we have an archive of it.
